### ISSUE TITLE
Ubuntu 24.04 wsl2, issues with script

### ISSUE THREAD

**Issue by br6** [slyfox1186/wsl2-kernel-build-script#1]
I get the following errors, under noble Numbat 24.04

Successfully downloaded the source code file "linux-msft-wsl-5.15.146.1"

Installing missing packages: aria2 cmake debootstrap g++-s390x-linux-gnu gcc-s390x-linux-gnu gdb-multiarch libcap-dev libncurses5 libncursesw5 libncursesw5-dev

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'libncurses-dev' instead of 'libncursesw5-dev'
E: Unable to locate package libncurses5
E: Unable to locate package libncursesw5
Downloading with wget...
wget: unrecognised option '--cqO'
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.
tar (child): wsl2-kernel-linux-msft-wsl-5.15.146.1.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
Failed to extract the archive. Exiting.

any workaround?

**Comment by slyfox1186** [comment]
Yeah, this was sadly missed by me. This should have been fixed a long time ago. If you still have issues let me know.
