### ISSUE TITLE
Feature for loading custom module for Realtek RTL8812AU Driver

### ISSUE THREAD

**Issue by karthikvijay5227** [slyfox1186/wsl2-kernel-build-script#2]
In the wsl 2 default kernel i am not able to add the custom module for rtl8812au driver for my wifi adapter but it shows error

`sudo apt install -y build-essential dkms linux-headers-$(uname -r)`

E: Unable to locate package linux-headers-5.15.153.1-microsoft-standard-WSL2
E: Couldn't find any package by glob 'linux-headers-5.15.153.1-microsoft-standard-WSL2'

So please do something.I am trying to load the rtl8812au driver of aircrack ng from github or apt install realtek-rtl88xxau-dkms

**Comment by slyfox1186** [comment]
I do not support this type of customization. I suggest you try another repository on GitHub if it exists. What you are asking for is a level of customization that I never claimed to provide or support.

You should try to figure out how to do this yourself if no one else has done this very specific thing you want.

Good luck.
